// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChD7v4fHF0WzI6DzjDGANuMV1mzy2XYrk',
    appId: '1:508321070950:web:4838f28f6b769f6aead2a7',
    messagingSenderId: '508321070950',
    projectId: 'gym-app-9e872',
    authDomain: 'gym-app-9e872.firebaseapp.com',
    storageBucket: 'gym-app-9e872.firebasestorage.app',
    measurementId: 'G-N6SM6ZL5S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWCpvtqPbeG4p7531XcZS1fQotpzJavXo',
    appId: '1:508321070950:android:ba45df0f6e5284bdead2a7',
    messagingSenderId: '508321070950',
    projectId: 'gym-app-9e872',
    storageBucket: 'gym-app-9e872.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChWSWQdTcXRZkFyEYPwXAG2F9t73fikSw',
    appId: '1:508321070950:ios:eac192d6b2958700ead2a7',
    messagingSenderId: '508321070950',
    projectId: 'gym-app-9e872',
    storageBucket: 'gym-app-9e872.firebasestorage.app',
    iosBundleId: 'com.example.ntl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChWSWQdTcXRZkFyEYPwXAG2F9t73fikSw',
    appId: '1:508321070950:ios:eac192d6b2958700ead2a7',
    messagingSenderId: '508321070950',
    projectId: 'gym-app-9e872',
    storageBucket: 'gym-app-9e872.firebasestorage.app',
    iosBundleId: 'com.example.ntl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChD7v4fHF0WzI6DzjDGANuMV1mzy2XYrk',
    appId: '1:508321070950:web:f23df345eb1ed515ead2a7',
    messagingSenderId: '508321070950',
    projectId: 'gym-app-9e872',
    authDomain: 'gym-app-9e872.firebaseapp.com',
    storageBucket: 'gym-app-9e872.firebasestorage.app',
    measurementId: 'G-HLDFYDTR6Z',
  );
}
